// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Activate(arg1:Array<string>):Promise<Array<main.actionResult>>;

export function AddCustomDir(arg1:string):Promise<main.detectResult>;

export function DetectAll():Promise<main.detectResult>;

export function RemoveCustomDir(arg1:string):Promise<main.detectResult>;

export function Restore(arg1:Array<string>):Promise<Array<main.actionResult>>;
