// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Activate(arg1) {
  return window['go']['main']['App']['Activate'](arg1);
}

export function AddCustomDir(arg1) {
  return window['go']['main']['App']['AddCustomDir'](arg1);
}

export function DetectAll() {
  return window['go']['main']['App']['DetectAll']();
}

export function RemoveCustomDir(arg1) {
  return window['go']['main']['App']['RemoveCustomDir'](arg1);
}

export function Restore(arg1) {
  return window['go']['main']['App']['Restore'](arg1);
}
